// KaySneakers Product & Mock Data
const PRODUCTS = [
  {
    id: 'kay-classic-black',
    name: 'Kay Classic',
    price: 189,
    comparePrice: 219,
    category: 'sneakers',
    badge: 'Best Seller',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=80',
    slug: 'kay-classic-black',
    colors: ['Black', 'White', 'Navy'],
    rating: 4.9,
    reviewCount: 342,
  },
  {
    id: 'kay-run-pro',
    name: 'Kay Run Pro',
    price: 219,
    category: 'sneakers',
    badge: 'New',
    image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80',
    slug: 'kay-run-pro',
    colors: ['Charcoal', 'Olive'],
    rating: 4.8,
    reviewCount: 128,
  },
  {
    id: 'kay-chelsea-boot',
    name: 'Kay Chelsea',
    price: 249,
    category: 'boots',
    badge: 'Best Seller',
    image: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800&q=80',
    slug: 'kay-chelsea-boot',
    colors: ['Black', 'Tan', 'Burgundy'],
    rating: 4.9,
    reviewCount: 256,
  },
  {
    id: 'kay-loafer-classic',
    name: 'Kay Loafer',
    price: 199,
    category: 'loafers',
    image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=800&q=80',
    slug: 'kay-loafer-classic',
    colors: ['Black', 'Brown', 'Cognac'],
    rating: 4.7,
    reviewCount: 89,
  },
  {
    id: 'kay-everyday-white',
    name: 'Kay Everyday',
    price: 169,
    category: 'sneakers',
    badge: 'New',
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80',
    slug: 'kay-everyday-white',
    colors: ['White', 'Gray'],
    rating: 4.8,
    reviewCount: 201,
  },
  {
    id: 'kay-chukka',
    name: 'Kay Chukka',
    price: 229,
    category: 'boots',
    image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&q=80',
    slug: 'kay-chukka',
    colors: ['Navy', 'Tan'],
    rating: 4.6,
    reviewCount: 67,
  },
  {
    id: 'kay-slip-on',
    name: 'Kay Slip-On',
    price: 179,
    category: 'loafers',
    badge: 'New',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
    slug: 'kay-slip-on',
    colors: ['Black', 'White'],
    rating: 4.9,
    reviewCount: 312,
  },
  {
    id: 'kay-ankle-boot',
    name: 'Kay Ankle',
    price: 239,
    category: 'boots',
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80',
    slug: 'kay-ankle-boot',
    colors: ['Black', 'Brown'],
    rating: 4.7,
    reviewCount: 94,
  },
];

// Search index for predictive search
const SEARCH_INDEX = [
  ...PRODUCTS.map(p => ({ type: 'product', ...p })),
  { type: 'collection', title: 'Sneakers', url: 'collections.html?c=sneakers' },
  { type: 'collection', title: 'Boots', url: 'collections.html?c=boots' },
  { type: 'collection', title: 'Loafers', url: 'collections.html?c=loafers' },
  { type: 'page', title: 'Size Guide', url: 'size-guide.html' },
  { type: 'page', title: 'Fit Guarantee', url: 'fit-guarantee.html' },
];
